### ISSUE TITLE
'Wallet with name 'X' already exists.

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/x42-Server#1] opened 2020-01-20 16:29 UTC
When creating a new xServer wallet a freezing bug presents itself.
xServer fresh install, no parameters changed (including testnet), there is a version of Fullnode .19 installed on this same machine.

1. Go to xServer
2. Click on Create Main Wallet (which is not capitalized by the way)
3. Enter the password and seed words, confirm seed words, click confirm.
4. See this window hanging, it doesn't go away even when you click OK
![image](https://user-images.githubusercontent.com/59352730/72742137-dc3f9680-3b87-11ea-93de-83d2e4530aea.png)

Expected behavior
The wallet is expected to move forward from this point into the server itself.

 - OS: Windows 10 completely up to date
 - Browser: Chrome
 - Version: 79.0.3945.117

**Comment by DennisAMenace** [comment] 2020-01-21 14:27
Both you and Myke have reported this, however, I cannot reproduce. 

Can you try on a box that does not have .19 installed?

**Comment by DennisAMenace** [comment] 2020-01-21 18:08
Closing this, as it appears to be related to and old version of x42 Core being installed on @Gabriel-x42 and @Myke500 tests.

**Closed as completed by DennisAMenace** 2020-01-21 18:08 UTC
Labels: bug, question
